# Generated by Django 6.0.3 on 2026-04-30 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ldea', '0023_person_educational_level_person_professional_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandReduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('treatment', models.TextField(blank=True)),
                ('cases', models.CharField(max_length=100)),
                ('injection_substance', models.CharField(max_length=10)),
                ('drug_test', models.TextField(blank=True)),
                ('psychotherapeutic_intervention', models.CharField(max_length=255)),
                ('psychotropic_interventions', models.CharField(max_length=255)),
                ('comorbid_conditions', models.CharField(max_length=255)),
                ('route_of_administration', models.CharField(max_length=255)),
                ('refer_from', models.CharField(max_length=255)),
                ('admission_status', models.CharField(max_length=100)),
                ('refer_to', models.CharField(max_length=255)),
                ('prevention', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persons', models.ManyToManyField(to='ldea.person')),
            ],
        ),
    ]
