# Generated by Django 6.0.3 on 2026-05-03 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandreduction',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='demandreduction',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demandreduction',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
