# Generated by Django 6.0.3 on 2026-05-03 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moh', '0002_demandreduction_city_demandreduction_county_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandreduction',
            name='prevention',
        ),
    ]
