# Generated by Django 6.0.3 on 2026-05-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moh', '0003_remove_demandreduction_prevention'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandreduction',
            name='treatment_facility',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='demandreduction',
            name='type_of_treatment',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
