# Generated by Django 6.0.3 on 2026-05-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moh', '0004_demandreduction_treatment_facility_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prevention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('date', models.DateField()),
                ('district', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('sud_awareness', models.BooleanField(default=False)),
                ('sud_communities', models.TextField(blank=True, help_text='Enter community names separated by comma')),
                ('school_health_club', models.BooleanField(default=False)),
                ('school_names', models.TextField(blank=True, help_text='Enter school names separated by comma')),
                ('media_campaign', models.BooleanField(default=False)),
                ('media_details', models.TextField(blank=True)),
                ('harm_reduction', models.BooleanField(default=False)),
                ('harm_reduction_details', models.TextField(blank=True)),
                ('radio_talk_show', models.BooleanField(default=False)),
                ('radio_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
