# Generated by Django 6.0.3 on 2026-06-11 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moh', '0005_prevention'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('facility_code', models.CharField(max_length=50, unique=True)),
                ('facility_type', models.CharField(choices=[('inpatient', 'Inpatient Rehabilitation Center'), ('outpatient', 'Outpatient Treatment Center'), ('detox', 'Detoxification Center'), ('community', 'Community-Based Treatment Center'), ('hospital', 'Hospital-Based Treatment Unit'), ('private', 'Private Treatment Facility'), ('government', 'Government Treatment Facility')], max_length=50)),
                ('ownership_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private'), ('ngo', 'NGO'), ('faith_based', 'Faith-Based Organization')], max_length=50)),
                ('county', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('city_town', models.CharField(max_length=100)),
                ('physical_address', models.TextField()),
                ('contact_person', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('alternate_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('licensed', models.BooleanField(blank=True, default=False, null=True)),
                ('license_number', models.CharField(blank=True, max_length=100, null=True)),
                ('license_issue_date', models.DateField(blank=True, null=True)),
                ('license_expiry_date', models.DateField(blank=True, null=True)),
                ('total_beds', models.PositiveIntegerField(default=0)),
                ('male_beds', models.PositiveIntegerField(default=0)),
                ('female_beds', models.PositiveIntegerField(default=0)),
                ('adolescent_beds', models.PositiveIntegerField(default=0)),
                ('current_occupancy', models.PositiveIntegerField(default=0)),
                ('detoxification_services', models.BooleanField(default=False)),
                ('inpatient_services', models.BooleanField(default=False)),
                ('outpatient_services', models.BooleanField(default=False)),
                ('counseling_services', models.BooleanField(default=False)),
                ('family_therapy', models.BooleanField(default=False)),
                ('group_therapy', models.BooleanField(default=False)),
                ('medication_assisted_treatment', models.BooleanField(default=False)),
                ('mental_health_services', models.BooleanField(default=False)),
                ('vocational_training', models.BooleanField(default=False)),
                ('aftercare_services', models.BooleanField(default=False)),
                ('medical_doctors', models.PositiveIntegerField(default=0)),
                ('psychiatrists', models.PositiveIntegerField(default=0)),
                ('psychologists', models.PositiveIntegerField(default=0)),
                ('nurses', models.PositiveIntegerField(default=0)),
                ('counselors', models.PositiveIntegerField(default=0)),
                ('social_workers', models.PositiveIntegerField(default=0)),
                ('peer_support_workers', models.PositiveIntegerField(default=0)),
                ('operational_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20)),
                ('opening_hours', models.CharField(blank=True, max_length=255, null=True)),
                ('accepts_referrals', models.BooleanField(default=True)),
                ('emergency_services_available', models.BooleanField(default=False)),
                ('reporting_year', models.PositiveIntegerField()),
                ('reporting_quarter', models.CharField(blank=True, max_length=20, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
