# Generated by Django 6.0.3 on 2026-06-11 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moh', '0006_treatmentfacility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentfacility',
            name='operational_status',
        ),
    ]
