# Generated by Django 6.0.3 on 2026-06-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moh', '0007_remove_treatmentfacility_operational_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentfacility',
            name='operational_status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20),
        ),
    ]
