# Generated by Django 6.0.3 on 2026-03-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldea_user',
            name='full_name',
        ),
    ]
