# Generated by Django 6.0.3 on 2026-03-24 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('system_admin', 'System Admin'), ('moj_head', 'MOJ Head'), ('ldea_head', 'LDEA Head'), ('ldea_ops', 'LDEA Head of OPs'), ('officers', 'Officers'), ('ldea_head_of_it', 'LDEA Head of IT'), ('moh_head', 'MOH Head'), ('mog_head', 'MOG Head'), ('moys_head', 'MOYS Head')], max_length=30),
        ),
    ]
