# Generated by Django 6.0.3 on 2026-04-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_moh_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('moj_head', 'MOJ Head'), ('moj_officers', 'MOJ Officers'), ('moj_it_head', 'MOJ IT Head'), ('ldea_head', 'LDEA Head'), ('officers', 'Officers'), ('ldea_head_of_it', 'LDEA Head of IT'), ('moh_head', 'MOH Head'), ('moh_officers', 'MOH Officers'), ('mog_head', 'MOG Head'), ('moys_head', 'MOYS Head')], default='moj_it_head', max_length=30),
        ),
    ]
