# Generated by Django 6.0.3 on 2026-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moj_user',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
