# Generated by Django 6.0.3 on 2026-05-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_moj_user_identification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moj_user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
