# Generated by Django 6.0.3 on 2026-05-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_mog_user_moys_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('moj_head', 'MOJ Head'), ('moj_officers', 'MOJ Officers'), ('moj_it_head', 'MOJ IT Head'), ('ldea_head', 'LDEA Head'), ('officers', 'Officers'), ('ldea_head_of_it', 'LDEA Head of IT'), ('moh_head', 'MOH Head'), ('moh_officers', 'MOH Data Officers'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('lab_technician', 'Lab Technician'), ('mental_health_specialist', 'Mental Health Specialist'), ('mog_head', 'MOG Head'), ('mog_officers', 'MoG Head'), ('moys_head', 'MOYS Head'), ('moys_officers', 'MoYS Head')], default='moj_it_head', max_length=30),
        ),
    ]
