# Generated by Django 6.0.3 on 2026-05-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldea_user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ldea_user',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
