# Generated by Django 6.0.3 on 2026-05-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moh_user',
            name='unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
