# Generated by Django 6.0.3 on 2026-05-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_moh_user_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('moj_head', 'MOJ Head'), ('moj_officers', 'MOJ Officers'), ('moj_it_head', 'MOJ IT Head'), ('ldea_head', 'LDEA Head'), ('officers', 'Officers'), ('ldea_head_of_it', 'LDEA Head of IT'), ('moh_head', 'MOH Head'), ('moh_officers', 'MOH Data Officers'), ('mog_head', 'MOG Head'), ('mog_officers', 'MOG Officers'), ('moys_head', 'MOYS Head'), ('moys_officers', 'MoYS Head')], default='moj_it_head', max_length=30),
        ),
    ]
