# Generated by Django 6.0.3 on 2026-06-02 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0028_remove_victimhistory_case_number'),
        ('mog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyTracingVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_code', models.CharField(blank=True, max_length=100, null=True)),
                ('center_type', models.CharField(blank=True, choices=[('Orphanage', 'Orphanage'), ('Adoption Agency/Transit Home', 'Adoption Agency/Transit Home'), ('Safe Home', 'Safe Home'), ('Specialized Home', 'Specialized Home'), ('Other', 'Other')], max_length=100, null=True)),
                ('center_type_other', models.CharField(blank=True, max_length=255, null=True)),
                ('separated_child', models.BooleanField(default=False)),
                ('mother_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mother_alive', models.CharField(blank=True, max_length=50, null=True)),
                ('father_name', models.CharField(blank=True, max_length=255, null=True)),
                ('father_alive', models.CharField(blank=True, max_length=50, null=True)),
                ('guardian_alive', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_status', models.CharField(blank=True, max_length=100, null=True)),
                ('house_location', models.TextField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('address_information', models.TextField(blank=True, null=True)),
                ('child_life_information', models.TextField(blank=True, null=True)),
                ('child_memorable_events', models.TextField(blank=True, null=True)),
                ('child_id_evidence', models.BooleanField(default=False)),
                ('birth_certificate_evidence', models.BooleanField(default=False)),
                ('photos_evidence', models.BooleanField(default=False)),
                ('other_evidence', models.CharField(blank=True, max_length=255, null=True)),
                ('child_identification_information', models.TextField(blank=True, null=True)),
                ('separation_date', models.DateField(blank=True, null=True)),
                ('separation_address', models.TextField(blank=True, null=True)),
                ('separated_from_name', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship_to_child', models.CharField(blank=True, max_length=255, null=True)),
                ('separation_circumstances', models.TextField(blank=True, null=True)),
                ('main_cause_of_separation', models.TextField(blank=True, null=True)),
                ('traced_person_name', models.CharField(blank=True, max_length=255, null=True)),
                ('traced_person_age', models.PositiveIntegerField(blank=True, null=True)),
                ('traced_person_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('traced_person_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('traced_person_relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('traced_person_occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('wants_child', models.BooleanField(default=False)),
                ('able_to_take_care', models.BooleanField(default=False)),
                ('alternative_family_available', models.BooleanField(default=False)),
                ('agreement_take_child', models.BooleanField(default=False)),
                ('signature_name', models.CharField(blank=True, max_length=255, null=True)),
                ('child_return_information', models.TextField(blank=True, null=True)),
                ('caseworker_observation', models.TextField(blank=True, null=True)),
                ('caseworker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('caseworker_date', models.DateField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ldea.person')),
            ],
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='mog.familytracingverification')),
            ],
        ),
    ]
