# Generated by Django 6.0.3 on 2026-06-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mog', '0002_familytracingverification_familymember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familytracingverification',
            name='able_to_take_care',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='familytracingverification',
            name='alternative_family_available',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='familytracingverification',
            name='wants_child',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
