# Generated by Django 6.0.3 on 2026-06-03 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0028_remove_victimhistory_case_number'),
        ('mog', '0003_alter_familytracingverification_able_to_take_care_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_code', models.CharField(blank=True, max_length=100, null=True)),
                ('case_id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('current_address', models.TextField(blank=True, null=True)),
                ('caregiver_name', models.CharField(blank=True, max_length=255, null=True)),
                ('before_separation_address', models.TextField(blank=True, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('other_address_info', models.CharField(blank=True, max_length=255, null=True)),
                ('match_case', models.CharField(blank=True, max_length=50, null=True)),
                ('discrepancies', models.TextField(blank=True, null=True)),
                ('child_knows_adult', models.CharField(blank=True, max_length=50, null=True)),
                ('child_comments', models.TextField(blank=True, null=True)),
                ('recognize_photos', models.CharField(blank=True, max_length=50, null=True)),
                ('need_info', models.CharField(blank=True, max_length=50, null=True)),
                ('info_provided', models.CharField(blank=True, max_length=50, null=True)),
                ('wants_reunification', models.CharField(blank=True, max_length=50, null=True)),
                ('child_wishes_comments', models.TextField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, max_length=255, null=True)),
                ('recommendation_reason', models.TextField(blank=True, null=True)),
                ('caseworker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('caseworker_date', models.DateField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ldea.person')),
            ],
        ),
    ]
