# Generated by Django 6.0.3 on 2026-06-03 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0028_remove_victimhistory_case_number'),
        ('mog', '0004_beneficiaryverification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryHandover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reunification_type', models.CharField(max_length=100)),
                ('adult_verification', models.CharField(max_length=10)),
                ('child_verification', models.CharField(max_length=10)),
                ('relationship_verified', models.CharField(max_length=10)),
                ('ongoing_support_needed', models.CharField(max_length=10)),
                ('caseworker_name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('caregiver1_name', models.CharField(max_length=255)),
                ('caregiver1_sex', models.CharField(max_length=20)),
                ('caregiver1_relationship', models.CharField(max_length=255)),
                ('caregiver2_name', models.CharField(max_length=255)),
                ('caregiver2_sex', models.CharField(max_length=20)),
                ('caregiver2_relationship', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('town_village', models.CharField(max_length=255)),
                ('clan', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('reunification_date', models.DateField()),
                ('reunification_place', models.CharField(max_length=255)),
                ('consent_person', models.CharField(max_length=255)),
                ('child_name', models.CharField(max_length=255)),
                ('agreement_statement', models.TextField()),
                ('caseworker_signature', models.CharField(max_length=255)),
                ('receiver_signature', models.CharField(max_length=255)),
                ('witness_signature', models.CharField(max_length=255)),
                ('additional_information', models.TextField()),
                ('new_address_location', models.TextField()),
                ('signature_date', models.DateField()),
                ('signature_place', models.CharField(max_length=255)),
                ('siblings_reunified', models.TextField()),
                ('supervisor_name', models.CharField(max_length=255)),
                ('supervisor_position', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ldea.person')),
            ],
        ),
    ]
