# Generated by Django 6.0.3 on 2026-06-03 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0028_remove_victimhistory_case_number'),
        ('mog', '0005_beneficiaryhandover'),
    ]

    operations = [
        migrations.CreateModel(
            name='TracingActionTaken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracing_notes', models.TextField()),
                ('caseworker_name', models.CharField(max_length=255)),
                ('caseworker_date', models.DateField()),
                ('caseworker_signature', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracing_records', to='ldea.person')),
            ],
        ),
        migrations.CreateModel(
            name='TracingActionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_details', models.CharField(blank=True, max_length=255, null=True)),
                ('individual_traced', models.CharField(blank=True, max_length=255, null=True)),
                ('tracing_location', models.TextField(blank=True, null=True)),
                ('tracing_outcome', models.CharField(blank=True, max_length=100, null=True)),
                ('tracing_details', models.TextField(blank=True, null=True)),
                ('next_steps', models.TextField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('tracing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='mog.tracingactiontaken')),
            ],
        ),
    ]
