# Generated by Django 6.0.3 on 2026-06-05 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0028_remove_victimhistory_case_number'),
        ('mog', '0006_tracingactiontaken_tracingactiondetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUpVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_house', models.CharField(blank=True, max_length=255, null=True)),
                ('street', models.CharField(blank=True, max_length=255, null=True)),
                ('town', models.CharField(blank=True, max_length=255, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('county', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=50, null=True)),
                ('living_with', models.CharField(blank=True, max_length=255, null=True)),
                ('relationship', models.CharField(blank=True, max_length=255, null=True)),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('visit_number', models.IntegerField(blank=True, null=True)),
                ('child_seen', models.CharField(blank=True, max_length=10, null=True)),
                ('seen_alone', models.CharField(blank=True, max_length=10, null=True)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('previous_followup_date', models.DateField(blank=True, null=True)),
                ('followed_with', models.JSONField(blank=True, default=list, null=True)),
                ('purpose_of_followup', models.TextField(blank=True, null=True)),
                ('followup_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ldea.person')),
            ],
        ),
    ]
