# Generated by Django 6.0.3 on 2026-06-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mog', '0007_followupvisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followupvisit',
            old_name='living_with',
            new_name='agency',
        ),
        migrations.AddField(
            model_name='followupvisit',
            name='action_conducted',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='followupvisit',
            name='action_followed',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='followupvisit',
            name='action_service',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupvisit',
            name='appearance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='followupvisit',
            name='caregiver_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='followupvisit',
            name='caseworker_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='followupvisit',
            name='followed_through',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='followupvisit',
            name='frequently_sick',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='followupvisit',
            name='health_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupvisit',
            name='health_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='followupvisit',
            name='protection_issues',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupvisit',
            name='psychological_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='followupvisit',
            name='signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='followupvisit',
            name='situation_change',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
