# Generated by Django 6.0.3 on 2026-06-05 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mog', '0008_rename_living_with_followupvisit_agency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupvisit',
            name='child_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
