# Generated by Django 6.0.3 on 2026-06-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mog', '0009_followupvisit_child_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupvisit',
            name='visit_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
