# Generated by Django 6.0.3 on 2026-06-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mog', '0010_followupvisit_visit_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='familytracingverification',
            name='follow_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
