# Generated by Django 6.0.3 on 2026-06-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mog', '0014_tracingactiontaken_follow_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityoutreachreport',
            name='follow_county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
