# Generated by Django 6.0.3 on 2026-06-08 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0028_remove_victimhistory_case_number'),
        ('mog', '0015_communityoutreachreport_follow_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_county', models.CharField(blank=True, max_length=100, null=True)),
                ('case_id_number', models.CharField(max_length=100)),
                ('date_case_closed', models.DateField()),
                ('primary_reason', models.CharField(max_length=255)),
                ('closure_reason_details', models.TextField(blank=True)),
                ('case_opened_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('current_case_summary', models.TextField()),
                ('caregiver_name', models.CharField(blank=True, max_length=255)),
                ('aregiver_relationship', models.CharField(blank=True, max_length=255)),
                ('county', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('community', models.CharField(blank=True, max_length=255)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('caregiver_phone', models.CharField(blank=True, max_length=100)),
                ('closure_process', models.TextField()),
                ('child_agreed', models.BooleanField(default=False)),
                ('child_reason', models.TextField(blank=True)),
                ('caregiver_agreed', models.BooleanField(default=False)),
                ('caregiver_reason', models.TextField(blank=True)),
                ('followup_planned', models.BooleanField(default=False)),
                ('followup_reason', models.TextField(blank=True)),
                ('file_complete', models.BooleanField(default=False)),
                ('file_complete_reason', models.TextField(blank=True)),
                ('storage_method', models.CharField(choices=[('electronic', 'Electronic'), ('hardcopy', 'Hard Copy'), ('both', 'Both')], max_length=50)),
                ('file_storage_until', models.DateField(blank=True, null=True)),
                ('child_informed', models.BooleanField(default=False)),
                ('child_informed_reason', models.TextField(blank=True)),
                ('contact_person_details', models.TextField(blank=True)),
                ('caseworker_name', models.CharField(max_length=255)),
                ('caseworker_phone', models.CharField(max_length=100)),
                ('caseworker_signature', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_closures', to='ldea.person')),
            ],
        ),
        migrations.CreateModel(
            name='CaseClosureApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('child', 'Child'), ('caregiver', 'Caregiver'), ('caseworker', 'Caseworker'), ('supervisor', 'Supervisor')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('agency', models.CharField(blank=True, max_length=255)),
                ('contact_details', models.CharField(blank=True, max_length=255)),
                ('signature', models.CharField(blank=True, max_length=255)),
                ('case_closure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='mog.caseclosure')),
            ],
        ),
    ]
