# Generated by Django 6.0.3 on 2026-06-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mog', '0016_caseclosure_caseclosureapproval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caseclosure',
            old_name='aregiver_relationship',
            new_name='caregiver_relationship',
        ),
    ]
