# Generated by Django 6.0.3 on 2026-03-23 12:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('case_number', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('filing_date', models.DateField(auto_now_add=True)),
                ('court_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigation', 'Under Investigation'), ('charged', 'Charged'), ('closed', 'Closed')], default='open', max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DrugType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, help_text='E.g., Narcotic, Stimulant, Depressant', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('common_units', models.CharField(blank=True, help_text='E.g., grams, pills, ounces', max_length=50)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='ldea.county')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Arrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arrest_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('arrest_date', models.DateField()),
                ('arrest_time', models.TimeField(blank=True, null=True)),
                ('location_description', models.TextField(blank=True)),
                ('arresting_officer', models.CharField(max_length=255)),
                ('badge_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('charges', models.TextField(blank=True, help_text='Initial charges at arrest')),
                ('status', models.CharField(choices=[('detained', 'Detained'), ('released', 'Released'), ('transferred', 'Transferred to Court')], default='detained', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ldea.county')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ldea.district')),
                ('drug_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ldea.drugtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('evidence_type', models.CharField(choices=[('drug', 'Drug / Narcotic'), ('weapon', 'Weapon'), ('document', 'Document'), ('electronics', 'Electronics'), ('other', 'Other')], default='other', max_length=50)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('location_description', models.TextField(blank=True)),
                ('collected_by', models.CharField(blank=True, max_length=255)),
                ('badge_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('stored', 'Stored'), ('analyzed', 'Analyzed'), ('destroyed', 'Destroyed'), ('submitted_to_court', 'Submitted to Court')], default='stored', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('arrest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='ldea.arrest')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='ldea.cases')),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ldea.county')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ldea.district')),
                ('drug_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ldea.drugtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('person_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('other_name', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('national_id', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True)),
                ('occupation', models.CharField(blank=True, max_length=255)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20)),
                ('nationality', models.CharField(default='Liberian', max_length=100)),
                ('is_repeat_offender', models.BooleanField(default=False)),
                ('is_under_investigation', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='persons/')),
                ('remarks', models.TextField(blank=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ldea.county')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ldea.district')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CaseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('role', models.CharField(choices=[('suspect', 'Suspect'), ('victim', 'Victim'), ('witness', 'Witness')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='ldea.cases')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ldea.person')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='arrest',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrests', to='ldea.person'),
        ),
        migrations.CreateModel(
            name='Seizure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seizure_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('seizure_date', models.DateField()),
                ('seizure_time', models.TimeField(blank=True, null=True)),
                ('location_description', models.TextField(blank=True)),
                ('seized_by', models.CharField(max_length=255)),
                ('badge_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('stored', 'Stored in Evidence Room'), ('destroyed', 'Destroyed'), ('used_for_analysis', 'Used for Analysis'), ('transferred', 'Transferred to Court')], default='stored', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ldea.county')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ldea.district')),
                ('drug_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ldea.drugtype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='arrest',
            name='seizure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ldea.seizure'),
        ),
    ]
