# Generated by Django 6.0.3 on 2026-03-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0002_drugtype_dded_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drugtype',
            old_name='dded_by',
            new_name='added_by',
        ),
    ]
