# Generated by Django 6.0.3 on 2026-03-24 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0003_rename_dded_by_drugtype_added_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugRaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('reference_code', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('raid_date', models.DateField()),
                ('raid_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('total_arrests', models.PositiveIntegerField(default=0)),
                ('total_seizures', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_raids', to=settings.AUTH_USER_MODEL)),
                ('lead_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_raids', to=settings.AUTH_USER_MODEL)),
                ('team_members', models.ManyToManyField(blank=True, related_name='team_raids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-raid_date'],
            },
        ),
    ]
