# Generated by Django 6.0.3 on 2026-03-24 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_role'),
        ('ldea', '0004_drugraid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugraid',
            name='lead_officer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_raids', to='accounts.ldea_user'),
        ),
        migrations.AlterField(
            model_name='drugraid',
            name='team_members',
            field=models.ManyToManyField(blank=True, related_name='team_raids', to='accounts.ldea_user'),
        ),
    ]
