# Generated by Django 6.0.3 on 2026-03-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0005_alter_drugraid_lead_officer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.RemoveField(
            model_name='district',
            name='county',
        ),
        migrations.AlterField(
            model_name='arrest',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='arrest',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='seizure',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='County',
        ),
        migrations.DeleteModel(
            name='District',
        ),
    ]
