# Generated by Django 6.0.3 on 2026-03-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0006_alter_person_county_alter_seizure_county_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
