# Generated by Django 6.0.3 on 2026-03-24 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0008_remove_person_district_alter_person_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
