# Generated by Django 6.0.3 on 2026-03-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0009_person_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
