# Generated by Django 6.0.3 on 2026-03-24 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0010_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
