# Generated by Django 6.0.3 on 2026-03-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0011_alter_person_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='seizure',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='seizure/'),
        ),
    ]
