# Generated by Django 6.0.3 on 2026-03-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0012_seizure_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugtype',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='seizure/'),
        ),
    ]
