# Generated by Django 6.0.3 on 2026-03-25 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0013_drugtype_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='action_taken',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cases',
            name='substance',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
