# Generated by Django 6.0.3 on 2026-03-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0014_cases_action_taken_cases_substance'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='charge',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('investigation', 'Under Investigation'), ('charged', 'Charged'), ('closed', 'Closed')], default='Case pending at MOJ', max_length=50),
        ),
    ]
