# Generated by Django 6.0.3 on 2026-03-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0015_cases_charge_alter_cases_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='status',
            field=models.CharField(choices=[('pending', 'Case pending at MOJ'), ('investigation', 'Under Investigation'), ('closed', 'Closed')], default='Case pending at MOJ', max_length=50),
        ),
    ]
