# Generated by Django 6.0.3 on 2026-03-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0016_alter_cases_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrest',
            name='drug_type',
            field=models.CharField(blank=True, default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='arrest',
            name='seizure',
            field=models.CharField(blank=True, default=2, max_length=100),
            preserve_default=False,
        ),
    ]
