# Generated by Django 6.0.3 on 2026-03-27 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0017_alter_arrest_drug_type_alter_arrest_seizure'),
    ]

    operations = [
        migrations.AddField(
            model_name='cases',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
