# Generated by Django 6.0.3 on 2026-04-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0018_cases_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.CharField(choices=[('suspect', 'Suspect'), ('victim', 'Victim'), ('witness', 'Witness')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
