# Generated by Django 6.0.3 on 2026-04-03 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0019_person_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseparticipant',
            name='role',
        ),
        migrations.CreateModel(
            name='VictimHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(max_length=150)),
                ('sub_category', models.CharField(blank=True, max_length=150, null=True)),
                ('drug_link', models.CharField(blank=True, max_length=150, null=True)),
                ('incident_date', models.DateField()),
                ('incident_time', models.TimeField(blank=True, null=True)),
                ('incident_location', models.CharField(max_length=255)),
                ('injury_type', models.CharField(blank=True, max_length=150, null=True)),
                ('injury_severity', models.CharField(blank=True, max_length=50, null=True)),
                ('medical_attention', models.BooleanField(default=False)),
                ('hospitalized', models.BooleanField(default=False)),
                ('victim_drug_use', models.BooleanField(default=False)),
                ('forced_drug_use', models.BooleanField(default=False)),
                ('witness_name', models.CharField(blank=True, max_length=150, null=True)),
                ('witness_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('witness_statement', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victims', to='ldea.person')),
            ],
        ),
    ]
