# Generated by Django 6.0.3 on 2026-04-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0020_remove_caseparticipant_role_victimhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseparticipant',
            name='is_primary',
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='role',
            field=models.CharField(choices=[('suspect', 'Suspect'), ('victim', 'Victim'), ('witness', 'Witness')], default=2, max_length=20),
            preserve_default=False,
        ),
    ]
