# Generated by Django 6.0.3 on 2026-04-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0021_remove_caseparticipant_is_primary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseparticipant',
            name='status',
        ),
        migrations.RemoveField(
            model_name='caseparticipant',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='caseparticipant',
            name='is_primary',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='caseparticipant',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
