# Generated by Django 6.0.3 on 2026-04-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0022_remove_caseparticipant_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='educational_level',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='person',
            name='professional_status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='person',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('separated', 'Separated'), ('widowed', 'Widowed'), ('other', 'Other')], max_length=20),
        ),
    ]
