# Generated by Django 6.0.3 on 2026-05-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0023_person_educational_level_person_professional_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drugraid',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
