# Generated by Django 6.0.3 on 2026-05-02 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0024_drugraid_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugraid',
            name='reference_code',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
