# Generated by Django 6.0.3 on 2026-05-19 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0025_alter_drugraid_reference_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='drug_user',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
