# Generated by Django 6.0.3 on 2026-05-24 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0026_person_drug_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='victimhistory',
            old_name='witness_statement',
            new_name='secondary_substances',
        ),
        migrations.RemoveField(
            model_name='victimhistory',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='victimhistory',
            name='drug_link',
        ),
        migrations.RemoveField(
            model_name='victimhistory',
            name='forced_drug_use',
        ),
        migrations.RemoveField(
            model_name='victimhistory',
            name='hospitalized',
        ),
        migrations.RemoveField(
            model_name='victimhistory',
            name='incident_type',
        ),
        migrations.RemoveField(
            model_name='victimhistory',
            name='injury_severity',
        ),
        migrations.RemoveField(
            model_name='victimhistory',
            name='injury_type',
        ),
        migrations.RemoveField(
            model_name='victimhistory',
            name='medical_attention',
        ),
        migrations.RemoveField(
            model_name='victimhistory',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='victimhistory',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='victimhistory',
            name='victim_drug_use',
        ),
        migrations.RemoveField(
            model_name='victimhistory',
            name='witness_contact',
        ),
        migrations.RemoveField(
            model_name='victimhistory',
            name='witness_name',
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='age_first_used',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='arrest_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='case_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='dependency_level',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=20),
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='duration_of_addiction_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='frequency_of_use',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('occasional', 'Occasional')], max_length=50),
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='if_rehab_yes',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='last_used_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='mental_health_issues',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='method_of_use',
            field=models.CharField(blank=True, choices=[('smoking', 'Smoking'), ('injecting', 'Injecting'), ('oral', 'Oral'), ('snorting', 'Snorting'), ('inhaling', 'Inhaling'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='overdose_count',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='overdose_history',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='primary_substance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='rehab_history',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='type_of_drug_used',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='victimhistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='victimhistory',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='victim', to='ldea.person'),
        ),
    ]
