# Generated by Django 6.0.3 on 2026-05-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldea', '0027_rename_witness_statement_victimhistory_secondary_substances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='victimhistory',
            name='case_number',
        ),
    ]
