# Generated by Django 6.0.3 on 2026-04-01 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ldea', '0018_cases_county'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('update_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_trial', 'In Trial'), ('adjourned', 'Adjourned'), ('completed', 'Completed')], max_length=50)),
                ('next_hearing_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('court_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='ldea.cases')),
                ('updated_by', models.ForeignKey(limit_choices_to={'role': 'moj'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VictimDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('condition', models.CharField(max_length=255)),
                ('referred_to_moh', models.BooleanField(default=False)),
                ('referral_date', models.DateField(blank=True, null=True)),
                ('treatment_status', models.CharField(choices=[('pending', 'Pending'), ('in_treatment', 'In Treatment'), ('recovered', 'Recovered')], default='pending', max_length=100)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('participant', models.OneToOneField(limit_choices_to={'role': 'victim'}, on_delete=django.db.models.deletion.CASCADE, to='ldea.caseparticipant')),
                ('referred_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'moj'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
