# Generated by Django 6.0.3 on 2026-04-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtupdate',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courtupdate',
            name='court',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
