# Generated by Django 6.0.3 on 2026-04-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moj', '0002_courtupdate_county_courtupdate_court'),
    ]

    operations = [
        migrations.AddField(
            model_name='victimdetails',
            name='county',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
